export const ActionType = {
    GET_CART_ITEMS_NUMBERS: "GET_CART_ITEMS_NUMBERS",
    ADD_TO_CART : "ADD_TO_CART",
    DELETE_FROM_CART: "DELETE_FROM_CART",
    EMPTY_CART: "EMPTY_CART",
    DECREASE_QUANTITY: "DECREASE_QUANTITY",
    INCREASE_QUANTITY: "INCREASE_QUANTITY",
    GET_TOTAL_CART_AMOUNT: "GET_TOTAL_CART_AMOUNT",
    EMPTY_CART: "EMPTY_CART"
}